services:
  postgres:
    image: postgres:latest
    container_name: meu_postgres
    environment:
      POSTGRES_USER: meu_usuario
      POSTGRES_PASSWORD: minhasenha123
      POSTGRES_DB: meubanco
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
